#Identity
spring.application.name=flash-sale-backend

# Default to development profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}


# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



# Global Server port
server.port=8080