# Production Profile
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# JPA Performance Settings
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Server
server.port=${PORT:8080}

# Logging
logging.level.root=INFO
logging.level.com.shubham.flashsalebackend=INFO