# Database - Local hardcoded values for easy IDE testing
spring.datasource.url=jdbc:postgresql://localhost:5432/flash_sale_db
spring.datasource.username=postgres
spring.datasource.password=shubham12@#12

# JPA - Developer friendly
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging - Loud for debugging
logging.level.com.shubham.flashsaleengine=DEBUG